# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/addinedu/amr_ws/aris_team5/Aris_Team5/src/store_package/ui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.loginBtn = QtWidgets.QPushButton(Dialog)
        self.loginBtn.setGeometry(QtCore.QRect(130, 220, 89, 25))
        self.loginBtn.setObjectName("loginBtn")
        self.hostLabel = QtWidgets.QLabel(Dialog)
        self.hostLabel.setGeometry(QtCore.QRect(20, 90, 67, 17))
        self.hostLabel.setObjectName("hostLabel")
        self.domainIDLabel = QtWidgets.QLabel(Dialog)
        self.domainIDLabel.setGeometry(QtCore.QRect(20, 140, 71, 17))
        self.domainIDLabel.setObjectName("domainIDLabel")
        self.hostLine = QtWidgets.QLineEdit(Dialog)
        self.hostLine.setGeometry(QtCore.QRect(110, 90, 113, 25))
        self.hostLine.setText("")
        self.hostLine.setReadOnly(True)
        self.hostLine.setObjectName("hostLine")
        self.domainIDLine = QtWidgets.QLineEdit(Dialog)
        self.domainIDLine.setGeometry(QtCore.QRect(110, 140, 113, 25))
        self.domainIDLine.setObjectName("domainIDLine")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginBtn.setText(_translate("Dialog", "Login"))
        self.hostLabel.setText(_translate("Dialog", "Host"))
        self.domainIDLabel.setText(_translate("Dialog", "Domain ID"))
